/**
 * The flags the flagpole can fly, generated by island/pixel/flags.py —
 * do not edit by hand.
 *
 * The code is also the sprite suffix: `flagpole_1_de` is the pole flying the
 * German flag. Adding one here and re-running the generators is all it takes.
 */

export interface IslandFlag {
  code: string;
  name: string;
  /** One character per pixel, keyed in FLAG_COLORS. */
  rows: readonly string[];
}

export const FLAG_WIDTH = 16;
export const FLAG_HEIGHT = 10;

export const FLAG_COLORS: Record<string, string> = {
  w: "#F4F4F2",
  k: "#1C1C1C",
  r: "#D42B32",
  R: "#A31620",
  b: "#2B4EA2",
  B: "#16306B",
  c: "#6CA9DE",
  y: "#F2C230",
  o: "#E8792B",
  g: "#188A4A",
  G: "#0E5C33",
  n: "#7B6A52",
};

export const ISLAND_FLAGS: readonly IslandFlag[] = [
  { code: "de", name: "Germany", rows: ["kkkkkkkkkkkkkkkk", "kkkkkkkkkkkkkkkk", "kkkkkkkkkkkkkkkk", "kkkkkkkkkkkkkkkk", "rrrrrrrrrrrrrrrr", "rrrrrrrrrrrrrrrr", "rrrrrrrrrrrrrrrr", "yyyyyyyyyyyyyyyy", "yyyyyyyyyyyyyyyy", "yyyyyyyyyyyyyyyy"] },
  { code: "tr", name: "Turkey", rows: ["rrrrrrrrrrrrrrrr", "rrrrrrrrrrrrrrrr", "rrrwwwwrrrrrrrrr", "rrwwrrrrwrrrrrrr", "rrwwrrrrrrwrrrrr", "rrwwrrrrrrwrrrrr", "rrwwrrrrwrrrrrrr", "rrrwwwwrrrrrrrrr", "rrrrrrrrrrrrrrrr", "rrrrrrrrrrrrrrrr"] },
  { code: "ua", name: "Ukraine", rows: ["bbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbb", "yyyyyyyyyyyyyyyy", "yyyyyyyyyyyyyyyy", "yyyyyyyyyyyyyyyy", "yyyyyyyyyyyyyyyy", "yyyyyyyyyyyyyyyy"] },
  { code: "sy", name: "Syria", rows: ["gggggggggggggggg", "gggggggggggggggg", "gggggggggggggggg", "wwwwwwwwwwwwwwww", "wwwwrwwwrwwwrwww", "wwwrrrwrrrwrrrww", "wwwwrwwwrwwwrwww", "kkkkkkkkkkkkkkkk", "kkkkkkkkkkkkkkkk", "kkkkkkkkkkkkkkkk"] },
  { code: "ro", name: "Romania", rows: ["bbbbbbyyyyyrrrrr", "bbbbbbyyyyyrrrrr", "bbbbbbyyyyyrrrrr", "bbbbbbyyyyyrrrrr", "bbbbbbyyyyyrrrrr", "bbbbbbyyyyyrrrrr", "bbbbbbyyyyyrrrrr", "bbbbbbyyyyyrrrrr", "bbbbbbyyyyyrrrrr", "bbbbbbyyyyyrrrrr"] },
  { code: "pl", name: "Poland", rows: ["wwwwwwwwwwwwwwww", "wwwwwwwwwwwwwwww", "wwwwwwwwwwwwwwww", "wwwwwwwwwwwwwwww", "wwwwwwwwwwwwwwww", "rrrrrrrrrrrrrrrr", "rrrrrrrrrrrrrrrr", "rrrrrrrrrrrrrrrr", "rrrrrrrrrrrrrrrr", "rrrrrrrrrrrrrrrr"] },
  { code: "af", name: "Afghanistan", rows: ["kkkkkrrrrrrggggg", "kkkkkrrrrrrggggg", "kkkkkrrrrrrggggg", "kkkkkrrwwrrggggg", "kkkkkrwwwwrggggg", "kkkkkrwwwwrggggg", "kkkkkrwrrwrggggg", "kkkkkrrrrrrggggg", "kkkkkrrrrrrggggg", "kkkkkrrrrrrggggg"] },
  { code: "it", name: "Italy", rows: ["ggggggwwwwwrrrrr", "ggggggwwwwwrrrrr", "ggggggwwwwwrrrrr", "ggggggwwwwwrrrrr", "ggggggwwwwwrrrrr", "ggggggwwwwwrrrrr", "ggggggwwwwwrrrrr", "ggggggwwwwwrrrrr", "ggggggwwwwwrrrrr", "ggggggwwwwwrrrrr"] },
  { code: "bg", name: "Bulgaria", rows: ["wwwwwwwwwwwwwwww", "wwwwwwwwwwwwwwww", "wwwwwwwwwwwwwwww", "gggggggggggggggg", "gggggggggggggggg", "gggggggggggggggg", "rrrrrrrrrrrrrrrr", "rrrrrrrrrrrrrrrr", "rrrrrrrrrrrrrrrr", "rrrrrrrrrrrrrrrr"] },
  { code: "hr", name: "Croatia", rows: ["rrrrrrrrrrrrrrrr", "rrrrrrrrrrrrrrrr", "rrrrrrrrrrrrrrrr", "rrrrrrwrwrrrrrrr", "wwwwwwrwrwwwwwww", "wwwwwwwrwrwwwwww", "wwwwwwrwrwwwwwww", "bbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbb"] },
  { code: "xk", name: "Kosovo", rows: ["BBBBBBBBBBBBBBBB", "BBBBBwBwBwBBBBBB", "BBBwBBBBBBBwBBBB", "BBBBBByyyyBBBBBB", "BBBBByyyyyyBBBBB", "BBBBByyyyyyBBBBB", "BBBBBByyyyBBBBBB", "BBBBBBByyBBBBBBB", "BBBBBBBBBBBBBBBB", "BBBBBBBBBBBBBBBB"] },
  { code: "in", name: "India", rows: ["oooooooooooooooo", "oooooooooooooooo", "oooooooooooooooo", "oooooooooooooooo", "wwwwwwwBBwwwwwww", "wwwwwwwBBwwwwwww", "wwwwwwwwwwwwwwww", "gggggggggggggggg", "gggggggggggggggg", "gggggggggggggggg"] },
  { code: "gr", name: "Greece", rows: ["bbwwbbbbbbbbbbbb", "bbwwbbwwwwwwwwww", "wwwwwwbbbbbbbbbb", "wwwwwwwwwwwwwwww", "bbwwbbbbbbbbbbbb", "bbwwbbwwwwwwwwww", "bbbbbbbbbbbbbbbb", "wwwwwwwwwwwwwwww", "bbbbbbbbbbbbbbbb", "wwwwwwwwwwwwwwww"] },
  { code: "rs", name: "Serbia", rows: ["rrrrrrrrrrrrrrrr", "rrrrrrrrrrrrrrrr", "rrrrrrrrrrrrrrrr", "rrrryyrrrrrrrrrr", "bbbbrrbbbbbbbbbb", "bbbbrrbbbbbbbbbb", "bbbbrrbbbbbbbbbb", "wwwwyywwwwwwwwww", "wwwwwwwwwwwwwwww", "wwwwwwwwwwwwwwww"] },
  { code: "iq", name: "Iraq", rows: ["rrrrrrrrrrrrrrrr", "rrrrrrrrrrrrrrrr", "rrrrrrrrrrrrrrrr", "wwwwwwwwwwwwwwww", "wwwwwggggggwwwww", "wwwwwwggggwwwwww", "wwwwwwwwwwwwwwww", "kkkkkkkkkkkkkkkk", "kkkkkkkkkkkkkkkk", "kkkkkkkkkkkkkkkk"] },
  { code: "ru", name: "Russia", rows: ["wwwwwwwwwwwwwwww", "wwwwwwwwwwwwwwww", "wwwwwwwwwwwwwwww", "wwwwwwwwwwwwwwww", "bbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbb", "bbbbbbbbbbbbbbbb", "rrrrrrrrrrrrrrrr", "rrrrrrrrrrrrrrrr", "rrrrrrrrrrrrrrrr"] },
  { code: "ba", name: "Bosnia", rows: ["BBBBByyyyyyyyyyy", "BBBBwByyyyyyyyyy", "BBBBBwByyyyyyyyy", "BBBBBBwByyyyyyyy", "BBBBBBBwByyyyyyy", "BBBBBBBBwByyyyyy", "BBBBBBBBBwByyyyy", "BBBBBBBBBBwByyyy", "BBBBBBBBBBBwByyy", "BBBBBBBBBBBBwByy"] },
  { code: "es", name: "Spain", rows: ["rrrrrrrrrrrrrrrr", "rrrrrrrrrrrrrrrr", "yyyyyyyyyyyyyyyy", "yyyyyyyyyyyyyyyy", "yyyyyyyyyyyyyyyy", "yyyyyyyyyyyyyyyy", "yyyyyyyyyyyyyyyy", "rrrrrrrrrrrrrrrr", "rrrrrrrrrrrrrrrr", "rrrrrrrrrrrrrrrr"] },
  { code: "hu", name: "Hungary", rows: ["rrrrrrrrrrrrrrrr", "rrrrrrrrrrrrrrrr", "rrrrrrrrrrrrrrrr", "rrrrrrrrrrrrrrrr", "wwwwwwwwwwwwwwww", "wwwwwwwwwwwwwwww", "wwwwwwwwwwwwwwww", "gggggggggggggggg", "gggggggggggggggg", "gggggggggggggggg"] },
  { code: "mk", name: "North Macedonia", rows: ["yrrrrrryyrrrrrry", "ryrrrrryyrrrrryr", "rryrrrryyrrrryrr", "rrryryyyyyyryrrr", "yyyyyyyyyyyyyyyy", "yyyyyyyyyyyyyyyy", "rrryryyyyyyryrrr", "rryrrrryyrrrryrr", "ryrrrrryyrrrrryr", "yrrrrrryyrrrrrry"] },
  { code: "vn", name: "Vietnam", rows: ["rrrrrrrrrrrrrrrr", "rrrrrrrrrrrrrrrr", "rrrrrrryyrrrrrrr", "rrrrrrryyrrrrrrr", "rrrryyyyyyyyrrrr", "rrrrryyyyyyrrrrr", "rrrrrryyyyrrrrrr", "rrrrrryrryrrrrrr", "rrrrryrrrryrrrrr", "rrrrrrrrrrrrrrrr"] },
  { code: "ir", name: "Iran", rows: ["gggggggggggggggg", "gggggggggggggggg", "gggggggggggggggg", "wwwwwwwwwwwwwwww", "wwwwwwwrrwwwwwww", "wwwwwwrrrrwwwwww", "wwwwwwwwwwwwwwww", "rrrrrrrrrrrrrrrr", "rrrrrrrrrrrrrrrr", "rrrrrrrrrrrrrrrr"] },
  { code: "cn", name: "China", rows: ["rrrrrrrrrrrrrrrr", "rrryrrryrrrrrrrr", "rryyyrrrrrrrrrrr", "ryyyyyrryrrrrrrr", "rryyyrrrrrrrrrrr", "rrryrrrryrrrrrrr", "rrrrrrryrrrrrrrr", "rrrrrrrrrrrrrrrr", "rrrrrrrrrrrrrrrr", "rrrrrrrrrrrrrrrr"] },
  { code: "ma", name: "Morocco", rows: ["rrrrrrrrrrrrrrrr", "rrrrrrrrrrrrrrrr", "rrrrrrrggrrrrrrr", "rrrrrrrggrrrrrrr", "rrrrggggggggrrrr", "rrrrrggrrggrrrrr", "rrrrrrggggrrrrrr", "rrrrrrgrrgrrrrrr", "rrrrrgrrrrgrrrrr", "rrrrrrrrrrrrrrrr"] },
  { code: "al", name: "Albania", rows: ["rrrrrrrrrrrrrrrr", "rrrrkkrrrrkkrrrr", "rrrkkkrrrrkkkrrr", "rrrrrkkrrkkrrrrr", "rrkkkkkkkkkkkkrr", "rrrkkkkkkkkkkrrr", "rrrrkkkkkkkkrrrr", "rrrrrrkkkkrrrrrr", "rrrrrkkkkkkrrrrr", "rrrrrrrrrrrrrrrr"] },
  { code: "at", name: "Austria", rows: ["rrrrrrrrrrrrrrrr", "rrrrrrrrrrrrrrrr", "rrrrrrrrrrrrrrrr", "rrrrrrrrrrrrrrrr", "wwwwwwwwwwwwwwww", "wwwwwwwwwwwwwwww", "wwwwwwwwwwwwwwww", "rrrrrrrrrrrrrrrr", "rrrrrrrrrrrrrrrr", "rrrrrrrrrrrrrrrr"] },
  { code: "pt", name: "Portugal", rows: ["ggggggrrrrrrrrrr", "ggggggrrrrrrrrrr", "ggggyyyrrrrrrrrr", "gggywwwyrrrrrrrr", "gggywrwyrrrrrrrr", "gggywwwyrrrrrrrr", "ggggyyyrrrrrrrrr", "ggggggrrrrrrrrrr", "ggggggrrrrrrrrrr", "ggggggrrrrrrrrrr"] },
  { code: "lb", name: "Lebanon", rows: ["rrrrrrrrrrrrrrrr", "rrrrrrrrrrrrrrrr", "wwwwwwwwwwwwwwww", "wwwwwwwggwwwwwww", "wwwwwwggggwwwwww", "wwwwwggggggwwwww", "wwwwggggggggwwww", "wwwwwwwggwwwwwww", "rrrrrrrrrrrrrrrr", "rrrrrrrrrrrrrrrr"] },
  { code: "er", name: "Eritrea", rows: ["rrgggggggggggggg", "rrrrrggggggggggg", "rrrrrrrrgggggggg", "rrrrrrrrrrrggggg", "ryyrrrrrrrrrrrgg", "ryyrrrrrrrrrrrcc", "rrrrrrrrrrrccccc", "rrrrrrrrcccccccc", "rrrrrccccccccccc", "rrcccccccccccccc"] },
  { code: "pk", name: "Pakistan", rows: ["wwwwgggggggggggg", "wwwwgggggggggggg", "wwwwggggggwwwggg", "wwwwgggggwwggggg", "wwwwggggwggggwgg", "wwwwggggwggggggg", "wwwwgggggwwggggg", "wwwwggggggwwwggg", "wwwwgggggggggggg", "wwwwgggggggggggg"] },
];
