const {
  withAppDelegate,
  withDangerousMod,
  withInfoPlist,
  withPodfile,
  withPodfileProperties,
} = require("expo/config-plugins");
const fs = require("fs");
const path = require("path");

const PODFILE_MARKER = "# @generated by withGoalsNativeConfig";
const SCENE_LIFECYCLE_MARKER = "// @generated by withGoalsNativeConfig: UIScene lifecycle";
const PODFILE_DEPLOYMENT_TARGET_FIX = `

    ${PODFILE_MARKER}
    # Xcode 27 rejects dependency targets below iOS 15. Align older resource
    # bundles with the app target after every clean Expo prebuild.
    installer.pods_project.targets.each do |pod_target|
      pod_target.build_configurations.each do |build_configuration|
        deployment_target =
          build_configuration.build_settings['IPHONEOS_DEPLOYMENT_TARGET']
        next if deployment_target.nil?
        next unless Gem::Version.new(deployment_target) < Gem::Version.new('15.1')

        build_configuration.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.1'
      end
    end
`;
const WIDGET_POD_BLOCK_PATTERN =
  /target "ExpoWidgetsTarget" do[\s\S]*?\nend(?=\s*$)/;
const NATIVE_WIDGET_POD_BLOCK = `target "ExpoWidgetsTarget" do
    # The Live Activity UI is native SwiftUI. Keeping React Native and
    # JavaScriptCore out of this memory-constrained extension prevents iOS
    # Jetsam termination while the Dynamic Island is rendered.
end`;

function useNativeWidgetExtension(contents) {
  if (!WIDGET_POD_BLOCK_PATTERN.test(contents)) {
    throw new Error("Could not find ExpoWidgetsTarget in the generated Podfile.");
  }
  return contents.replace(
    WIDGET_POD_BLOCK_PATTERN,
    NATIVE_WIDGET_POD_BLOCK,
  );
}

function addSceneLifecycleToAppDelegate(contents) {
  if (contents.includes(SCENE_LIFECYCLE_MARKER)) {
    return contents;
  }

  const classDeclaration = "class AppDelegate: ExpoAppDelegate {\n  var window: UIWindow?";
  if (!contents.includes(classDeclaration)) {
    throw new Error("Could not find Expo's AppDelegate class declaration.");
  }

  let nextContents = contents.replace(
    classDeclaration,
    `class AppDelegate: ExpoAppDelegate {
  ${SCENE_LIFECYCLE_MARKER}
  var window: UIWindow?
  var initialLaunchOptions: [UIApplication.LaunchOptionsKey: Any]?`,
  );

  const launchBlock = `#if os(iOS) || os(tvOS)
    window = UIWindow(frame: UIScreen.main.bounds)
    factory.startReactNative(
      withModuleName: "main",
      in: window,
      launchOptions: launchOptions)
#endif
`;
  if (!nextContents.includes(launchBlock)) {
    throw new Error("Could not find Expo's React Native window launch block.");
  }
  nextContents = nextContents.replace(
    launchBlock,
    `    // UIKit creates and owns the window through SceneDelegate on iOS 27+.
    // Keep the process-wide React Native factory ready for that scene.
    initialLaunchOptions = launchOptions
`,
  );

  const linkingMarker = "  // Linking API";
  if (!nextContents.includes(linkingMarker)) {
    throw new Error("Could not find Expo's AppDelegate linking marker.");
  }
  nextContents = nextContents.replace(
    linkingMarker,
    `  public func application(
    _ application: UIApplication,
    configurationForConnecting connectingSceneSession: UISceneSession,
    options: UIScene.ConnectionOptions
  ) -> UISceneConfiguration {
    let configuration = UISceneConfiguration(
      name: "Default Configuration",
      sessionRole: connectingSceneSession.role
    )
    configuration.delegateClass = SceneDelegate.self
    return configuration
  }

${linkingMarker}`,
  );

  const reactNativeDelegateMarker =
    "\nclass ReactNativeDelegate: ExpoReactNativeFactoryDelegate {";
  if (!nextContents.includes(reactNativeDelegateMarker)) {
    throw new Error("Could not find Expo's ReactNativeDelegate declaration.");
  }

  return nextContents.replace(
    reactNativeDelegateMarker,
    `

class SceneDelegate: UIResponder, UIWindowSceneDelegate {
  var window: UIWindow?

  private var appDelegate: AppDelegate? {
    UIApplication.shared.delegate as? AppDelegate
  }

  func scene(
    _ scene: UIScene,
    willConnectTo session: UISceneSession,
    options connectionOptions: UIScene.ConnectionOptions
  ) {
    guard
      let windowScene = scene as? UIWindowScene,
      let appDelegate,
      let factory = appDelegate.reactNativeFactory
    else {
      return
    }

    let window = UIWindow(windowScene: windowScene)
    self.window = window
    appDelegate.window = window

    var launchOptions = appDelegate.initialLaunchOptions ?? [:]
    if let urlContext = connectionOptions.urlContexts.first {
      launchOptions[.url] = urlContext.url
      if let sourceApplication = urlContext.options.sourceApplication {
        launchOptions[.sourceApplication] = sourceApplication
      }
      if let annotation = urlContext.options.annotation {
        launchOptions[.annotation] = annotation
      }
    }
    if let userActivity = connectionOptions.userActivities.first {
      launchOptions[.userActivityDictionary] = [
        "UIApplicationLaunchOptionsUserActivityTypeKey": userActivity.activityType,
        "UIApplicationLaunchOptionsUserActivityKey": userActivity
      ]
    }

    factory.startReactNative(
      withModuleName: "main",
      in: window,
      launchOptions: launchOptions.isEmpty ? nil : launchOptions
    )
  }

  func sceneDidBecomeActive(_ scene: UIScene) {
    appDelegate?.applicationDidBecomeActive(UIApplication.shared)
  }

  func sceneWillResignActive(_ scene: UIScene) {
    appDelegate?.applicationWillResignActive(UIApplication.shared)
  }

  func sceneWillEnterForeground(_ scene: UIScene) {
    appDelegate?.applicationWillEnterForeground(UIApplication.shared)
  }

  func sceneDidEnterBackground(_ scene: UIScene) {
    appDelegate?.applicationDidEnterBackground(UIApplication.shared)
  }

  func scene(_ scene: UIScene, openURLContexts URLContexts: Set<UIOpenURLContext>) {
    guard let appDelegate else {
      return
    }

    for context in URLContexts {
      var options: [UIApplication.OpenURLOptionsKey: Any] = [
        .openInPlace: context.options.openInPlace
      ]
      if let sourceApplication = context.options.sourceApplication {
        options[.sourceApplication] = sourceApplication
      }
      if let annotation = context.options.annotation {
        options[.annotation] = annotation
      }
      _ = appDelegate.application(
        UIApplication.shared,
        open: context.url,
        options: options
      )
    }
  }

  func scene(_ scene: UIScene, continue userActivity: NSUserActivity) {
    _ = appDelegate?.application(
      UIApplication.shared,
      continue: userActivity,
      restorationHandler: { _ in }
    )
  }
}
${reactNativeDelegateMarker}`,
  );
}

/**
 * Keeps the generated iOS capabilities aligned with what Goals actually uses.
 * expo-task-manager adds generic background-fetch even though this app only
 * runs location tasks, and Expo adds the bundle identifier beside an identical
 * explicit URL scheme. Both are normalized after package plugins run.
 */
module.exports = function withGoalsNativeConfig(config) {
  const isProductionBuild =
    process.env.GOALS_PRODUCTION_BUILD === "true";
  const bundleIdentifier = config.ios?.bundleIdentifier;

  // React Native 0.83's precompiled React.xcframework and the source-built
  // RCTSwiftUI pods both contain the same SwiftUI bridge classes in this
  // dependency graph. A physical iPhone aborts at launch when both copies are
  // loaded. Expo's supported opt-out builds RN Core and RCTSwiftUI together
  // from source, leaving exactly one implementation in the app binary.
  let nextConfig = withPodfileProperties(config, (propertiesConfig) => {
    propertiesConfig.modResults["ios.buildReactNativeFromSource"] = "true";
    return propertiesConfig;
  });

  nextConfig = withInfoPlist(nextConfig, (infoPlistConfig) => {
    const plist = infoPlistConfig.modResults;

    // Apps linked with the iOS 27 SDK abort before JavaScript starts unless
    // they adopt UIKit's scene-based lifecycle. The matching SceneDelegate is
    // generated into AppDelegate.swift below.
    plist.UIApplicationSceneManifest = {
      UIApplicationSupportsMultipleScenes: false,
      UISceneConfigurations: {
        UIWindowSceneSessionRoleApplication: [
          {
            UISceneClassName: "UIWindowScene",
            UISceneConfigurationName: "Default Configuration",
            UISceneDelegateClassName:
              "$(PRODUCT_MODULE_NAME).SceneDelegate",
          },
        ],
      },
    };

    if (Array.isArray(plist.UIBackgroundModes)) {
      plist.UIBackgroundModes = [
        ...new Set(plist.UIBackgroundModes.filter((mode) => mode !== "fetch")),
      ];
    }

    if (Array.isArray(plist.CFBundleURLTypes)) {
      plist.CFBundleURLTypes = plist.CFBundleURLTypes
        .map((entry) => ({
          ...entry,
          CFBundleURLSchemes: Array.isArray(entry.CFBundleURLSchemes)
            ? [
                ...new Set(
                  entry.CFBundleURLSchemes.filter(
                    (scheme) =>
                      typeof scheme !== "string" ||
                      (
                        !scheme.startsWith("exp+") &&
                        (!isProductionBuild || scheme !== bundleIdentifier)
                      ),
                  ),
                ),
              ]
            : entry.CFBundleURLSchemes,
        }))
        .filter(
          (entry) =>
            !Array.isArray(entry.CFBundleURLSchemes) ||
            entry.CFBundleURLSchemes.length > 0,
        );
    }

    if (isProductionBuild) {
      delete plist.NSBonjourServices;
      delete plist.NSLocalNetworkUsageDescription;
    }
    delete plist.NSMicrophoneUsageDescription;
    return infoPlistConfig;
  });

  nextConfig = withAppDelegate(nextConfig, (appDelegateConfig) => {
    if (appDelegateConfig.modResults.language !== "swift") {
      throw new Error("Goals requires a Swift AppDelegate.");
    }
    appDelegateConfig.modResults.contents = addSceneLifecycleToAppDelegate(
      appDelegateConfig.modResults.contents,
    );
    return appDelegateConfig;
  });

  nextConfig = withPodfile(nextConfig, (podfileConfig) => {
    let contents = useNativeWidgetExtension(
      podfileConfig.modResults.contents,
    );
    if (contents.includes(PODFILE_MARKER)) {
      podfileConfig.modResults.contents = contents;
      return podfileConfig;
    }

    const postInstallEnd = contents.lastIndexOf("\n  end\nend");
    if (postInstallEnd < 0) {
      throw new Error(
        "Could not find Expo's post_install block in the generated Podfile.",
      );
    }

    contents =
      contents.slice(0, postInstallEnd) +
      PODFILE_DEPLOYMENT_TARGET_FIX +
      contents.slice(postInstallEnd);
    podfileConfig.modResults.contents = contents;
    return podfileConfig;
  });

  nextConfig = withDangerousMod(nextConfig, [
    "ios",
    async (dangerousConfig) => {
      const templatePath = path.join(
        dangerousConfig.modRequest.projectRoot,
        "native",
        "FocusLiveActivityWidget.swift",
      );
      const destinationPath = path.join(
        dangerousConfig.modRequest.platformProjectRoot,
        "ExpoWidgetsTarget",
        "index.swift",
      );
      fs.copyFileSync(templatePath, destinationPath);
      return dangerousConfig;
    },
  ]);

  return nextConfig;
};
