#!/usr/bin/env python3
"""
Turn the plant PNGs into a TypeScript module the app can draw.

React Native blurs PNGs when it scales them up, so the sprites ship as pixel
rows instead: one character per pixel, drawn as SVG rectangles at runtime (the
same trick as src/components/PixelArt.tsx). That stays sharp at any size and
animates without getting soft.

Usage, from the repo root:
    python3 island/pixel/export_sprites.py island/pixel/plants src/components/grow/plantSprites.ts
"""

import json
import os
import sys

from PIL import Image

SHADOW_RGBA = (0, 0, 0, 64)
SHADOW_CHAR = "z"
# The shadow character is taken out of the alphabet instead of being skipped while
# assigning: skipping handed the same letter to the next colour (39 colours broke it).
ALPHABET = "".join(
    c for c in "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"
    if c != SHADOW_CHAR
)


def main(plant_dir, out_path, prefix="PLANT"):
    with open(os.path.join(plant_dir, "manifest.json")) as handle:
        manifest = json.load(handle)

    colors = {}
    sprites = {}
    for entry in sorted(manifest, key=lambda e: (e["key"], e["level"])):
        image = Image.open(os.path.join(plant_dir, entry["file"])).convert("RGBA")
        rows = []
        for y in range(image.height):
            row = []
            for x in range(image.width):
                pixel = image.getpixel((x, y))
                if pixel[3] == 0:
                    row.append(".")
                elif pixel == SHADOW_RGBA:
                    row.append(SHADOW_CHAR)
                else:
                    hex_color = "#%02X%02X%02X" % pixel[:3]
                    if hex_color not in colors:
                        colors[hex_color] = ALPHABET[len(colors)]
                    row.append(colors[hex_color])
            rows.append("".join(row))
        # Named by the file stem so variants of one object — the flagpole with
        # each flag — each get their own picture under their own name.
        sprites[entry["file"][: -len(".png")]] = {
            "w": image.width,
            "h": image.height,
            "rows": rows,
        }

    lines = [
        "/**",
        " * Pixel rows of the island plants, generated by island/pixel/export_sprites.py.",
        " * Do not edit by hand: the next run of the generator overwrites this file.",
        " *",
        " * One character per pixel, `.` is transparent and `z` is the ground shadow",
        " * (black at 25 %). Drawn as SVG rectangles, so the sprites stay sharp at every",
        " * size — React Native would blur a scaled-up PNG.",
        " */",
        "",
        f"export const {prefix}_COLORS: Record<string, string> = {{",
    ]
    for hex_color, char in sorted(colors.items(), key=lambda item: item[1]):
        lines.append(f'  {char}: "{hex_color}",')
    lines.append("};")
    lines.append("")
    lines.append('/** Character drawn as the ground shadow. */')
    lines.append(f'export const {prefix}_SHADOW = "{SHADOW_CHAR}";')
    lines.append("")
    lines.append(f"export interface {prefix.capitalize()}SpriteData {{")
    lines.append("  w: number;")
    lines.append("  h: number;")
    lines.append("  rows: string[];")
    lines.append("}")
    lines.append("")
    lines.append("/** Key is `<object>_<level>`, as in island/pixel/. */")
    lines.append(
        f"export const {prefix}_SPRITES: Record<string, {prefix.capitalize()}SpriteData> = {{"
    )
    for name, sprite in sprites.items():
        lines.append(f'  {name}: {{')
        lines.append(f'    w: {sprite["w"]},')
        lines.append(f'    h: {sprite["h"]},')
        lines.append("    rows: [")
        for row in sprite["rows"]:
            lines.append(f'      "{row}",')
        lines.append("    ],")
        lines.append("  },")
    lines.append("};")
    lines.append("")

    with open(out_path, "w") as handle:
        handle.write("\n".join(lines))
    pixels = sum(s["w"] * s["h"] for s in sprites.values())
    print(f"{len(sprites)} sprites, {len(colors)} colours, {pixels} pixels -> {out_path}")


if __name__ == "__main__":
    plants = sys.argv[1] if len(sys.argv) > 1 else "island/pixel/plants"
    out = sys.argv[2] if len(sys.argv) > 2 else "src/components/grow/plantSprites.ts"
    main(plants, out, sys.argv[3] if len(sys.argv) > 3 else "PLANT")
